[HTTP]
HTTPServerEnabled = {{HTTPServerEnabled}}
UseSSL = {{UseSSL}}
HTTPServerIP = "{{HTTPServerIP}}"
HTTPServerPort = {{HTTPServerPort}}
SSLCertPath = "./.ssl/HttpServer/cert.pem"
SSLKeyPath = "./.ssl/HttpServer/key.pem"

[Misc]
SendErrorsShowMessage = {{SendErrorsShowMessage}}
SendErrors = {{SendErrors}}
ImScaredOfUpdates = {{ImScaredOfUpdates}}

[General]
Description = "{{Description}}"
ResourceFolder = "{{ResourceFolder}}"
Map = "{{Map}}"
MaxPlayers = {{MaxPlayers}}
Port = {{Port}}
Private = {{Private}}
Debug = {{Debug}}
Name = "{{Name}}"
LogChat = {{LogChat}}
MaxCars = {{MaxCars}}
AuthKey = "{{AuthKey}}"